# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # Needed because we use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X github.com/rsinnet/docker-credential-gcr/config.Version={{.Version}}"
    goarch:
      - amd64
      - arm64
      - 386
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
